sudo: true
language: go
go:
  - "1.10.x"

_dev_vars: &dev_vars
  # Dev jobs like `lint` and `test` will not run on tags and master.
  if: tag IS blank
  branches:
    except:
      - master

jobs:

  allow_failures:
    - stage: lint

  include:

    - stage: lint
      name: Run gofmt.
      script:
        - make gofmt
      <<: *dev_vars

    - stage: lint
      name: Run golint.
      before_script:
        - sudo apt update
        - sudo apt install -y golint
      script:
        - make golint
      <<: *dev_vars

    - stage: test
      name: Unit test and coverage report.
      script:
        - make unittest_coverage
      <<: *dev_vars

    - stage: build
      name: Build and push docker image.
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # Build tagged and latest images and push them to Docker Hub.
        - make docker_release

    - stage: build
      name: Build and push binaries to GitHub.
      if: branch = master
      script:
        - make cli_release
      deploy:
        provider: releases
        api_key: "$GHA_TOKEN"
        file_glob: true
        file: dist/*.gz
        skip_cleanup: true
