sudo: true
language: go
go:
  - "1.10.x"

jobs:

  allow_failures:
    - stage: lint

  include:

    - stage: lint
      name: Run gofmt.
      script:
        - make gofmt

    - stage: test
      name: Unit test and coverage report.
      script:
        - make unittest_coverage

    - stage: build
      name: Build and push docker image.
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # Build tagged and latest images and push them to Docker Hub.
        - make docker_release

    - stage: build
      name: Build and push binaries to GitHub.
      if: branch = master
      script:
        - make cli_release
      deploy:
        provider: releases
        api_key: "$GHA_TOKEN"
        file_glob: true
        file: dist/*.gz
        skip_cleanup: true
