sudo: true
language: go
go:
  - "1.10.x"

jobs:
  include:

    - stage: Run unit test.
      script:
        - make test

    - stage: Build and push docker image.
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # Build tagged and latest images and push them to Docker Hub.
        - make docker_release

    - stage: Build and push binaries to GitHub.
      if: branch = master
      script:
        - make cli_release
      deploy:
        provider: releases
        api_key: "$GHA_TOKEN"
        file_glob: true
        file: dist/*.gz
        skip_cleanup: true
